name: frc_district_rank
description: Helpful app to see where your team stands


publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  tba_api_dart_dio_client:
    git: https://github.com/jr1221/tba_api_dart_dio_client
  dio: ^5.1.1
  expandable: ^5.0.1 # abandoned?
  flutter_linkify: ^5.0.2 # abandoned?
  url_launcher: ^6.1.10
  settings_ui: ^2.0.2 # abandoned?
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  bot_toast: ^4.0.3
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
