name: frc_district_rank
description: Helpful app to see where your team stands


publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  tba_api_dart_dio_client:
    git: https://github.com/jr1221/tba_api_dart_dio_client
  dio:
  expandable: ^5.0.1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.5
  settings_ui: ^2.0.2
  easy_refresh: ^3.0.4+2
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider:

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
